### ISSUE TITLE
possible Bug: No default processor selected when using @Optional

### ISSUE THREAD

**Issue by thomas-mc-work** [dkschlos/super-csv-declarative#4] opened 2016-08-03 11:15 UTC
When my field has the annotation `@Optional` then no corresponding processor for the data type is selected. E.g. `ParseInt` is missing for all `int`and `Integer` fields. I would expect to have it created by the library, except when override it manually.

My workaround is to define the Processor manually:

    @CsvField(order = 7)
    @Optional(order = 0)
    @ParseChar(order = 1)
    private Character myValue;

**Comment by dkschlos** [comment] 2016-08-04 05:54
That is not a bug but could be a possible improvement. It is implemented this way on purpose since one might use another processor than the default ones to do the conversion.
The only situation where ParseXXX-annotations are added automatically is when there is no processor-annotation at all. In all other cases we would need to check the return type of the last CellProcessor which can not be done right now because of type-erasure and thus would require major changes.
Suggestions welcome.

**Comment by thomas-mc-work** [comment] 2016-08-04 06:18
What about declaring a marker interface for data type conversion processors (like `ParseInt`). If there is none of them defined then automatically select a default one derived by the variable type (via `BeanCellProcessorExtractor::mapFieldToDefaultProcessor()`).

**Comment by dkschlos** [comment] 2016-08-04 08:53
Changing processors is out of scope of this project since it is merely an addon to SuperCSV.
But your suggestion is great anyway because there are already marker interfaces for primitive type conversions in the framework as far as i remember :-)

**Comment by thomas-mc-work** [comment] 2016-08-04 09:54
Alright, sounds good. Otherwise you could not mark the processors (which makes sense) but maybe the annotations.

**Closed** 2016-08-14 16:41 UTC
Labels: enhancement
